const constants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_FORM_UPDATE: "LOGIN_FORM_UPDATE",
  XHR_REQUEST: "XHR_REQUEST",
  APP_START: "APP_START",
  INITIALIZE: "INITIALIZE",
}

export default constants
